export const users = [
  {
    _id: '66b625ae2e7f62600a334b9f',
    index: 0,
    guid: '32bc4c62-5c7f-45ae-b4b1-9030c21770fa',
    isActive: false,
    balance: '$3,516.40',
    picture: 'http://placehold.it/32x32',
    age: 20,
    eyeColor: 'blue',
    name: 'Caitlin Fry',
    gender: 'female',
    company: 'CUIZINE',
    email: 'caitlinfry@cuizine.com',
    phone: '+1 (974) 533-2086',
    address:
      '299 Dinsmore Place, Dellview, Federated States Of Micronesia, 6129',
    about:
      'Officia elit anim aute reprehenderit irure et officia laborum sit amet. Velit non do adipisicing aliquip nisi. Non commodo magna enim officia sunt irure nisi adipisicing ullamco incididunt cupidatat ut reprehenderit. Dolore veniam incididunt ex mollit non qui reprehenderit ea commodo nisi ullamco. In in cupidatat ipsum ipsum officia dolor adipisicing ad ad velit.\r\n',
    registered: '2016-09-12T02:18:50 -02:00',
    latitude: -24.808698,
    longitude: 121.320039,
    tags: ['culpa', 'pariatur', 'irure', 'aute', 'reprehenderit', 'elit', 'do'],
    friends: [
      {
        id: 0,
        name: 'Kathrine Hamilton',
      },
      {
        id: 1,
        name: 'Walls Simon',
      },
      {
        id: 2,
        name: 'Ida Porter',
      },
    ],
    greeting: 'Hello, Caitlin Fry! You have 3 unread messages.',
    favoriteFruit: 'banana',
  },
  {
    _id: '66b625ae6ee84fec36bb34c5',
    index: 1,
    guid: 'd67ffefd-e96b-45e6-8c81-8696903f8133',
    isActive: true,
    balance: '$1,837.40',
    picture: 'http://placehold.it/32x32',
    age: 36,
    eyeColor: 'brown',
    name: 'Melanie David',
    gender: 'female',
    company: 'QUILITY',
    email: 'melaniedavid@quility.com',
    phone: '+1 (976) 415-2130',
    address: '759 Ivan Court, Levant, Louisiana, 1818',
    about:
      'Labore amet qui velit cillum sint. Dolore mollit velit velit velit ipsum ad dolore occaecat nisi consectetur laboris cupidatat minim. Irure culpa labore mollit cillum eu reprehenderit adipisicing voluptate minim non laborum excepteur irure laboris. Exercitation reprehenderit laborum eiusmod eiusmod consequat duis et. Eu minim cillum duis cupidatat aliquip ad in exercitation. Non duis cillum est quis quis. Cillum occaecat incididunt eiusmod velit tempor et incididunt nisi voluptate ipsum.\r\n',
    registered: '2020-06-16T04:26:24 -02:00',
    latitude: -47.611267,
    longitude: 87.371697,
    tags: ['labore', 'culpa', 'est', 'minim', 'in', 'id', 'proident'],
    friends: [
      {
        id: 0,
        name: 'Chelsea Coffey',
      },
      {
        id: 1,
        name: 'Lyons Ayala',
      },
      {
        id: 2,
        name: 'Mclaughlin Jordan',
      },
    ],
    greeting: 'Hello, Melanie David! You have 4 unread messages.',
    favoriteFruit: 'apple',
  },
  {
    _id: '66b625ae5e8efb2a4c26b720',
    index: 2,
    guid: '0a688e07-2281-4b40-afc7-382c5551160f',
    isActive: false,
    balance: '$3,821.36',
    picture: 'http://placehold.it/32x32',
    age: 38,
    eyeColor: 'green',
    name: 'Nona William',
    gender: 'female',
    company: 'HONOTRON',
    email: 'nonawilliam@honotron.com',
    phone: '+1 (915) 479-3196',
    address: '549 Guernsey Street, Innsbrook, Nebraska, 8187',
    about:
      'Consequat proident fugiat duis ullamco excepteur. Consequat ut voluptate duis sint amet aute exercitation enim mollit. Est est cupidatat cupidatat proident exercitation enim. Amet ipsum cupidatat deserunt duis ex aliquip.\r\n',
    registered: '2022-02-11T08:51:22 -02:00',
    latitude: -43.639659,
    longitude: 76.081189,
    tags: ['do', 'pariatur', 'sint', 'consequat', 'veniam', 'et', 'minim'],
    friends: [
      {
        id: 0,
        name: 'Eloise Allen',
      },
      {
        id: 1,
        name: 'Barnett Haynes',
      },
      {
        id: 2,
        name: 'Leanna Fuller',
      },
    ],
    greeting: 'Hello, Nona William! You have 8 unread messages.',
    favoriteFruit: 'apple',
  },
  {
    _id: '66b625ae4c829f75d3152f09',
    index: 3,
    guid: '9ab501e3-980b-4253-bf78-be185bf1b0b5',
    isActive: true,
    balance: '$3,272.85',
    picture: 'http://placehold.it/32x32',
    age: 36,
    eyeColor: 'brown',
    name: 'Alta Norton',
    gender: 'female',
    company: 'GEEKKO',
    email: 'altanorton@geekko.com',
    phone: '+1 (847) 563-3893',
    address: '242 Cozine Avenue, Dexter, Arkansas, 2912',
    about:
      'Consectetur dolor non amet aliqua non et amet magna. Excepteur incididunt sunt aliqua ad duis tempor nisi proident laboris culpa est quis minim. Ullamco Lorem cillum exercitation quis. Lorem do nisi consectetur duis sint labore aute laboris. Ad proident et do mollit aliqua esse est consectetur. Eu ad in amet nulla sint.\r\n',
    registered: '2020-10-03T08:29:09 -02:00',
    latitude: 36.962424,
    longitude: 34.298182,
    tags: [
      'quis',
      'consectetur',
      'proident',
      'incididunt',
      'ex',
      'incididunt',
      'laboris',
    ],
    friends: [
      {
        id: 0,
        name: 'Dina King',
      },
      {
        id: 1,
        name: 'Barton Buck',
      },
      {
        id: 2,
        name: 'Reyna Hewitt',
      },
    ],
    greeting: 'Hello, Alta Norton! You have 6 unread messages.',
    favoriteFruit: 'apple',
  },
  {
    _id: '66b625ae0f4072dda2f6b603',
    index: 4,
    guid: 'e583e255-7811-412e-97e1-5da07b39cf66',
    isActive: true,
    balance: '$3,079.63',
    picture: 'http://placehold.it/32x32',
    age: 32,
    eyeColor: 'brown',
    name: 'Noemi Barlow',
    gender: 'female',
    company: 'CEPRENE',
    email: 'noemibarlow@ceprene.com',
    phone: '+1 (991) 589-2328',
    address: '694 Butler Place, Matthews, Kentucky, 2540',
    about:
      'Magna culpa cupidatat duis voluptate non quis. Pariatur veniam minim aute aute incididunt ipsum ut eiusmod pariatur qui ut excepteur. Adipisicing occaecat ipsum exercitation aliquip dolor magna eu cupidatat ullamco aliqua Lorem. Et adipisicing non cillum in ea ex dolor reprehenderit aute cupidatat magna tempor cupidatat qui. Pariatur ad laboris amet occaecat non anim fugiat laboris adipisicing duis occaecat qui.\r\n',
    registered: '2014-09-08T08:53:49 -03:00',
    latitude: 86.576432,
    longitude: -86.853763,
    tags: ['ex', 'ut', 'amet', 'minim', 'enim', 'Lorem', 'laborum'],
    friends: [
      {
        id: 0,
        name: 'Wolf Becker',
      },
      {
        id: 1,
        name: 'Deann Rodriguez',
      },
      {
        id: 2,
        name: 'Kaitlin Foreman',
      },
    ],
    greeting: 'Hello, Noemi Barlow! You have 10 unread messages.',
    favoriteFruit: 'apple',
  },
  {
    _id: '66b625ae5665231f2b4ec5de',
    index: 5,
    guid: '25436b03-623c-447d-b19f-7fa503ba7aae',
    isActive: true,
    balance: '$3,267.59',
    picture: 'http://placehold.it/32x32',
    age: 21,
    eyeColor: 'green',
    name: 'Deidre Burnett',
    gender: 'female',
    company: 'HOTCAKES',
    email: 'deidreburnett@hotcakes.com',
    phone: '+1 (983) 597-2870',
    address: '817 Tompkins Place, Hessville, District Of Columbia, 2163',
    about:
      'Excepteur Lorem quis nulla amet Lorem in labore pariatur veniam enim mollit. Id laborum est proident excepteur commodo duis. Sint deserunt nulla laborum aliquip ut ex sit consequat Lorem labore. Enim ea nisi dolor exercitation. Velit amet magna sunt dolore velit et proident anim pariatur dolor anim sit aliquip.\r\n',
    registered: '2019-10-02T05:43:05 -02:00',
    latitude: -54.652741,
    longitude: 85.865923,
    tags: ['cillum', 'occaecat', 'irure', 'id', 'eiusmod', 'enim', 'ut'],
    friends: [
      {
        id: 0,
        name: 'Nita Fletcher',
      },
      {
        id: 1,
        name: 'Rosemary Hernandez',
      },
      {
        id: 2,
        name: 'Manning Mitchell',
      },
    ],
    greeting: 'Hello, Deidre Burnett! You have 7 unread messages.',
    favoriteFruit: 'banana',
  },
  {
    _id: '66b625ae134b1c9a9aca49af',
    index: 6,
    guid: 'e25b1fbb-951e-4e9b-92a9-5a9b2c966541',
    isActive: true,
    balance: '$1,577.04',
    picture: 'http://placehold.it/32x32',
    age: 37,
    eyeColor: 'green',
    name: 'Marla Moreno',
    gender: 'female',
    company: 'HINWAY',
    email: 'marlamoreno@hinway.com',
    phone: '+1 (875) 523-3720',
    address: '109 Village Road, Cloverdale, Maryland, 5851',
    about:
      'Aliquip sit in deserunt nulla pariatur cillum adipisicing Lorem exercitation veniam laboris. Irure et qui magna ut officia ea ex velit veniam reprehenderit eiusmod eu. Commodo culpa mollit nisi cillum pariatur aliqua pariatur officia voluptate veniam cupidatat ullamco. Sunt commodo incididunt excepteur sint nulla id ea irure. Anim consequat eu exercitation voluptate amet. Duis ullamco eu aliqua ipsum ipsum anim ea velit pariatur.\r\n',
    registered: '2024-05-12T04:06:33 -03:00',
    latitude: 88.677151,
    longitude: -35.887726,
    tags: [
      'do',
      'voluptate',
      'deserunt',
      'non',
      'elit',
      'minim',
      'reprehenderit',
    ],
    friends: [
      {
        id: 0,
        name: 'Key Murray',
      },
      {
        id: 1,
        name: 'Harrison Holloway',
      },
      {
        id: 2,
        name: 'Concetta Crane',
      },
    ],
    greeting: 'Hello, Marla Moreno! You have 1 unread messages.',
    favoriteFruit: 'apple',
  },
];
